// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class SalaryPredictAPI
{
    /// <summary>
    /// model input class for SalaryPredictAPI.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [LoadColumn(0)]
        [ColumnName(@"Age")]
        public float Age { get; set; }

        [LoadColumn(1)]
        [ColumnName(@"Gender")]
        public string Gender { get; set; }

        [LoadColumn(2)]
        [ColumnName(@"Education Level")]
        public string Education_Level { get; set; }

        [LoadColumn(3)]
        [ColumnName(@"Job Title")]
        public string Job_Title { get; set; }

        [LoadColumn(4)]
        [ColumnName(@"Years of Experience")]
        public float Years_of_Experience { get; set; }

        [LoadColumn(5)]
        [ColumnName(@"Salary")]
        public float Salary { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for SalaryPredictAPI.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"Age")]
        public float Age { get; set; }

        [ColumnName(@"Gender")]
        public float[] Gender { get; set; }

        [ColumnName(@"Education Level")]
        public float[] Education_Level { get; set; }

        [ColumnName(@"Job Title")]
        public float[] Job_Title { get; set; }

        [ColumnName(@"Years of Experience")]
        public float Years_of_Experience { get; set; }

        [ColumnName(@"Salary")]
        public float Salary { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"Score")]
        public float Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("SalaryPredictAPI.mlnet");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

}
